### ISSUE TITLE
Visualization Error

### ISSUE THREAD

**Issue by MichielPerneel** [AlexanderLabWHOI/EUKulele#40]
Hi @akrinos ,

I have EUKulele installed on our HPC, and it runs fine. However, it does not generate the figures when run with metatranscriptomic data. This is the traceback of the tax_vis.err:

```
(base) [vsc43619@gligar04 log]$ cat tax_vis.err 
Traceback (most recent call last):
  File "/apps/gent/RHEL8/zen2-ib/software/EUKulele/1.0.4-foss-2020b/bin/EUKulele", line 8, in <module>
    EUKulele.eukulele(string_arguments=' '.join(sys.argv[1:]))
  File "/apps/gent/RHEL8/zen2-ib/software/EUKulele/1.0.4-foss-2020b/lib/python3.8/site-packages/EUKulele/EUKulele_config.py", line 32, in eukulele
    EUKulele.EUKulele_main.main(str(string_arguments))
  File "/apps/gent/RHEL8/zen2-ib/software/EUKulele/1.0.4-foss-2020b/lib/python3.8/site-packages/EUKulele/EUKulele_main.py", line 309, in main
    manageEukulele(piece = "visualize_taxonomy", output_dir = output_dir,
  File "/apps/gent/RHEL8/zen2-ib/software/EUKulele/1.0.4-foss-2020b/lib/python3.8/site-packages/EUKulele/manage_steps.py", line 87, in manageEukulele
    manageTaxVisualization(output_dir, mets_or_mags, sample_dir, pep_ext, nt_ext,
  File "/apps/gent/RHEL8/zen2-ib/software/EUKulele/1.0.4-foss-2020b/lib/python3.8/site-packages/EUKulele/manage_steps.py", line 640, in manageTaxVisualization
    visualize_all_results(out_prefix, output_dir,
  File "/apps/gent/RHEL8/zen2-ib/software/EUKulele/1.0.4-foss-2020b/lib/python3.8/site-packages/EUKulele/visualize_results.py", line 369, in visualize_all_results
    lgd = ax1.legend(handles, labels, loc='upper center',\
  File "/apps/gent/RHEL8/zen2-ib/software/matplotlib/3.3.3-foss-2020b/lib/python3.8/site-packages/matplotlib/axes/_axes.py", line 417, in legend
    self.legend_ = mlegend.Legend(self, handles, labels, **kwargs)
TypeError: __init__() got an unexpected keyword argument 'bbox_inches'
```

The installation version of EUKulele is 1.0.4., I suspect this might be an old versioning issue?

**Comment by akrinos** [comment]
Hey @MichielPerneel - just noticed that this issue was still open - were you every able to figure this one out? Sorry for the delay in responding directly here!

**Comment by akrinos** [comment]
Hey @MichielPerneel , feel free to add additional details if you kept working on this problem :)
