### ISSUE TITLE
EukProt fails at taxonomy estimation step

### ISSUE THREAD

**Issue by cnatalie** [AlexanderLabWHOI/EUKulele#51]
Using `EUKulele 2.0.5,` taxonomic estimation completes using mmetsp as the database, but does not with EukProt. 

Here was the command:

`EUKulele -s /vortexfs1/omics/saito/BATS2019-clio-metaT/eukrhythmic_output/transdecoder_mega_merge_finalproteins -m mets --nucleotide_extension .cds --database eukprot --alignment_choice diamond --no_busco --consensus_proportion 0.97
`
And the error output in `output/log/tax_est_merged.err`:

```
Traceback (most recent call last):
  File "/vortexfs1/home/ncohen/.conda/envs/EUK14/lib/python3.7/site-packages/EUKulele/manage_steps.py", line 587, in manageTaxEstimation
    est_err_file,est_out_file)
  File "/vortexfs1/home/ncohen/.conda/envs/EUK14/lib/python3.7/site-packages/EUKulele/tax_placement.py", line 280, in place_taxonomy
    tax_table, classes = read_in_taxonomy(tax_file)
  File "/vortexfs1/home/ncohen/.conda/envs/EUK14/lib/python3.7/site-packages/EUKulele/tax_placement.py", line 69, in read_in_taxonomy
    tax_out.source_id = tax_out.source_id.astype(str)
  File "/vortexfs1/home/ncohen/.conda/envs/EUK14/lib/python3.7/site-packages/pandas/core/generic.py", line 5460, in __getattr__
    return object.__getattribute__(self, name)
AttributeError: 'DataFrame' object has no attribute 'source_id'

```

**Comment by franlat** [comment]
I have the same exact error running EUKulele 2.0.5 with EukProt. Any news on how to solve it?

**Comment by akrinos** [comment]
Hi there @franlat - @cnatalie and I are working on a revised EukProt DB! will update soon

**Comment by danilodileo** [comment]
Hi Arianna, 
I saw there is a new version of Eukprot v3 could it help to fix this issue by updating it?
