### ISSUE TITLE
Cant install from Mamba

### ISSUE THREAD

**Issue by blsteven** [AlexanderLabWHOI/EUKulele#52]
Installation fails with mamba with the following error:

nothing provides r 3.2.2* needed by r-magrittr-1.5-r3.2.2_0

**Comment by akrinos** [comment]
Hi there @blsteven - what version of EUKulele are you trying to install?

**Comment by blsteven** [comment]
Thanks in advance for the replies and help!

I was able to get the package to install by removing strict channel controls in conda. The mamba installation was successful, but now when I invoke Eukulele I get the following:

File "/Users/blaire/miniconda3/envs/EUKulele/bin/EUKulele", line 6, in <module>
    import EUKulele
  File "/Users/blaire/miniconda3/envs/EUKulele/lib/python3.7/site-packages/EUKulele/__init__.py", line 5, in <module>
    from EUKulele.EUKulele_main import *
  File "/Users/blaire/miniconda3/envs/EUKulele/lib/python3.7/site-packages/EUKulele/EUKulele_main.py", line 12, in <module>
    from EUKulele.download_database import downloadDatabase
  File "/Users/blaire/miniconda3/envs/EUKulele/lib/python3.7/site-packages/EUKulele/download_database.py", line 12, in <module>
    from EUKulele.manage_steps import createAlignmentDatabase
  File "/Users/blaire/miniconda3/envs/EUKulele/lib/python3.7/site-packages/EUKulele/manage_steps.py", line 19, in <module>
    from EUKulele.visualize_results import visualize_all_results
  File "/Users/blaire/miniconda3/envs/EUKulele/lib/python3.7/site-packages/EUKulele/visualize_results.py", line 9, in <module>
    import matplotlib.pyplot as plt
  File "/Users/blaire/miniconda3/envs/EUKulele/lib/python3.7/site-packages/matplotlib/pyplot.py", line 36, in <module>
    import matplotlib.colorbar
  File "/Users/blaire/miniconda3/envs/EUKulele/lib/python3.7/site-packages/matplotlib/colorbar.py", line 44, in <module>
    import matplotlib.contour as contour
  File "/Users/blaire/miniconda3/envs/EUKulele/lib/python3.7/site-packages/matplotlib/contour.py", line 17, in <module>
    import matplotlib.text as text
  File "/Users/blaire/miniconda3/envs/EUKulele/lib/python3.7/site-packages/matplotlib/text.py", line 16, in <module>
    from .textpath import TextPath  # Unused, but imported by others.
  File "/Users/blaire/miniconda3/envs/EUKulele/lib/python3.7/site-packages/matplotlib/textpath.py", line 11, in <module>
    from matplotlib.mathtext import MathTextParser
  File "/Users/blaire/miniconda3/envs/EUKulele/lib/python3.7/site-packages/matplotlib/mathtext.py", line 27, in <module>
    from PIL import Image
  File "/Users/blaire/miniconda3/envs/EUKulele/lib/python3.7/site-packages/PIL/Image.py", line 103, in <module>
    from . import _imaging as core
ImportError: dlopen(/Users/blaire/miniconda3/envs/EUKulele/lib/python3.7/site-packages/PIL/_imaging.cpython-37m-darwin.so, 2): Library not loaded: @rpath/libtiff.5.dylib
  Referenced from: /Users/blaire/miniconda3/envs/EUKulele/lib/python3.7/site-packages/PIL/_imaging.cpython-37m-darwin.so
  Reason: image not found
(EUKulele) blaire@x86_64-apple-darwin13 ~ % EUKulele
Traceback (most recent call last):
  File "/Users/blaire/miniconda3/envs/EUKulele/bin/EUKulele", line 6, in <module>
    import EUKulele
  File "/Users/blaire/miniconda3/envs/EUKulele/lib/python3.7/site-packages/EUKulele/__init__.py", line 5, in <module>
    from EUKulele.EUKulele_main import *
  File "/Users/blaire/miniconda3/envs/EUKulele/lib/python3.7/site-packages/EUKulele/EUKulele_main.py", line 12, in <module>
    from EUKulele.download_database import downloadDatabase
  File "/Users/blaire/miniconda3/envs/EUKulele/lib/python3.7/site-packages/EUKulele/download_database.py", line 12, in <module>
    from EUKulele.manage_steps import createAlignmentDatabase
  File "/Users/blaire/miniconda3/envs/EUKulele/lib/python3.7/site-packages/EUKulele/manage_steps.py", line 19, in <module>
    from EUKulele.visualize_results import visualize_all_results
  File "/Users/blaire/miniconda3/envs/EUKulele/lib/python3.7/site-packages/EUKulele/visualize_results.py", line 9, in <module>
    import matplotlib.pyplot as plt
  File "/Users/blaire/miniconda3/envs/EUKulele/lib/python3.7/site-packages/matplotlib/pyplot.py", line 36, in <module>
    import matplotlib.colorbar
  File "/Users/blaire/miniconda3/envs/EUKulele/lib/python3.7/site-packages/matplotlib/colorbar.py", line 44, in <module>
    import matplotlib.contour as contour
  File "/Users/blaire/miniconda3/envs/EUKulele/lib/python3.7/site-packages/matplotlib/contour.py", line 17, in <module>
    import matplotlib.text as text
  File "/Users/blaire/miniconda3/envs/EUKulele/lib/python3.7/site-packages/matplotlib/text.py", line 16, in <module>
    from .textpath import TextPath  # Unused, but imported by others.
  File "/Users/blaire/miniconda3/envs/EUKulele/lib/python3.7/site-packages/matplotlib/textpath.py", line 11, in <module>
    from matplotlib.mathtext import MathTextParser
  File "/Users/blaire/miniconda3/envs/EUKulele/lib/python3.7/site-packages/matplotlib/mathtext.py", line 27, in <module>
    from PIL import Image
  File "/Users/blaire/miniconda3/envs/EUKulele/lib/python3.7/site-packages/PIL/Image.py", line 103, in <module>
    from . import _imaging as core
ImportError: dlopen(/Users/blaire/miniconda3/envs/EUKulele/lib/python3.7/site-packages/PIL/_imaging.cpython-37m-darwin.so, 2): Library not loaded: @rpath/libtiff.5.dylib
  Referenced from: /Users/blaire/miniconda3/envs/EUKulele/lib/python3.7/site-packages/PIL/_imaging.cpython-37m-darwin.so
  Reason: image not found

**Comment by akrinos** [comment]
Hi @blsteven , this is really unusual! Could you send the command you used to install? Never seen this particular error before. I appreciate your patience!

**Comment by akrinos** [comment]
Hi @blsteven - leaving off the `-c akrinos` is the right call - sorry I didn't respond before, the Mac part threw me off a little bit. I've been trying to look into ways to make `EUKulele` more compatible on Mac systems. I think probably the challenge stems from the OS.
