### ISSUE TITLE
some runs fail when downloading gtdb and marmmetsp

### ISSUE THREAD

**Issue by danilodileo** [AlexanderLabWHOI/EUKulele#58]
HI,
I noticed that EUKulele doesn't provide the right files to run the workflow when it needs to download gtdb or marmmetsp databases. The run stops without any error message.

```
-2023-12-11 18:11:45--  https://www.dropbox.com/s/w1uv1j9qr63z3ac/taxonomy_table.txt?dl=1
Resolving www.dropbox.com (www.dropbox.com)... 162.125.70.18, 2620:100:6026:18::a27d:4612
Connecting to www.dropbox.com (www.dropbox.com)|162.125.70.18|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: /s/dl/w1uv1j9qr63z3ac/taxonomy_table.txt [following]
--2023-12-11 18:11:46--  https://www.dropbox.com/s/dl/w1uv1j9qr63z3ac/taxonomy_table.txt
Reusing existing connection to www.dropbox.com:443.
HTTP request sent, awaiting response... 302 Found
Location: https://uc281d8b9a3a1e00e82e9d226cd3.dl.dropboxusercontent.com/cd/0/get/CJORJn0t37WLKuHMonv1FjmF1pR2MnyVbbdZN4n1eQcPiauXcPmit2HOldxs84B_zcAvCrBpTGa388rm51Ar2q6ngz934EM6OyqMoIoA4ll-PBohZKj4BZcbC-I9jeV4BRE-e_KsWaAfX8GHJxFUtEy_/file?dl=1# [following]
--2023-12-11 18:11:46--  https://uc281d8b9a3a1e00e82e9d226cd3.dl.dropboxusercontent.com/cd/0/get/CJORJn0t37WLKuHMonv1FjmF1pR2MnyVbbdZN4n1eQcPiauXcPmit2HOldxs84B_zcAvCrBpTGa388rm51Ar2q6ngz934EM6OyqMoIoA4ll-PBohZKj4BZcbC-I9jeV4BRE-e_KsWaAfX8GHJxFUtEy_/file?dl=1
Resolving uc281d8b9a3a1e00e82e9d226cd3.dl.dropboxusercontent.com (uc281d8b9a3a1e00e82e9d226cd3.dl.dropboxusercontent.com)... 162.125.70.15, 2620:100:6026:15::a27d:460f
Connecting to uc281d8b9a3a1e00e82e9d226cd3.dl.dropboxusercontent.com (uc281d8b9a3a1e00e82e9d226cd3.dl.dropboxusercontent.com)|162.125.70.15|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 226422 (221K) [application/binary]
Saving to: ‘eukulele/marmmetsp/taxonomy-table.txt’

eukulele/marmmetsp/taxonomy-table.txt                     100%[====================================================================================================================================>] 221.12K  --.-KB/s    in 0.008s

2023-12-11 18:11:47 (27.4 MB/s) - ‘eukulele/marmmetsp/taxonomy-table.txt’ saved [226422/226422]

All reference files for MarRef-MMETSP downloaded to eukulele/marmmetsp
```

the resulting marmmetsp folder has inside two files: reference.pep.fa and taxonomy-table.txt.

If I understood correctly, the workflow stops because it lacks of other files like the protein.json.

I get the same issue with gtdb.

NB if I  already have all files for the database in a folder, the workflow works without any issue. So it's just the combination of download and run that doesn't work for this two db.

Thanks!

**Comment by cnatalie** [comment]
Hello @danilodileo, I just tried running EUKulele v2.0.0 with the marmmetsp database and all database files (including .json) are correctly downloaded. Can you provide the command you are using, and the EUKulele version?

**Comment by shanexuuu** [comment]
Hi I have the same problem.
Code : 	EUKulele --CPUs 80 --sample_dir eukulele/input -m mags -o eukulele/RL14_SK24_min1500 --reference_dir /SSD7TB_data/DB_Eukulele/marmmetsp --protein_extension faa
Version: v2.0.7

Also no .json.

Could you have any suggestion?

Many thanks!

**Comment by akrinos** [comment]
Hi @shanexuuu thanks for reporting this. It might have been some link that got broken in the 2.0.7 release. To clarify, you are also getting the fasta and TSV file, just not the JSON?

**Comment by shanexuuu** [comment]
Yes. That is correct.

Also I found a proteintab.err:
Traceback (most recent call last):
  File "/SSD7TB_data/miniconda3/envs/EUKulele/bin/EUKulele", line 8, in <module>
    EUKulele.eukulele(string_arguments=' '.join(sys.argv[1:]))
  File "/SSD7TB_data/miniconda3/envs/EUKulele/lib/python3.7/site-packages/EUKulele/EUKulele_config.py", line 32, in eukulele
    EUKulele.EUKulele_main.main(str(string_arguments))
  File "/SSD7TB_data/miniconda3/envs/EUKulele/lib/python3.7/site-packages/EUKulele/EUKulele_main.py", line 254, in main
    split("/")[0:-1]))
  File "/SSD7TB_data/miniconda3/envs/EUKulele/lib/python3.7/site-packages/EUKulele/download_database.py", line 101, in downloadDatabase
    rc1 = createProteinTable(create_protein_table_args)
  File "/SSD7TB_data/miniconda3/envs/EUKulele/lib/python3.7/site-packages/scripts/create_protein_table.py", line 88, in createProteinTable
    for record in SeqIO.parse(pepfile, "fasta"):
  File "/SSD7TB_data/miniconda3/envs/EUKulele/lib/python3.7/site-packages/Bio/SeqIO/Interfaces.py", line 73, in __next__
    return next(self.records)
  File "/SSD7TB_data/miniconda3/envs/EUKulele/lib/python3.7/site-packages/Bio/SeqIO/FastaIO.py", line 198, in iterate
    for title, sequence in SimpleFastaParser(handle):
  File "/SSD7TB_data/miniconda3/envs/EUKulele/lib/python3.7/site-packages/Bio/SeqIO/FastaIO.py", line 47, in SimpleFastaParser
    for line in handle:
  File "/SSD7TB_data/miniconda3/envs/EUKulele/lib/python3.7/codecs.py", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte

Thanks a lot！

发件人: akrinos ***@***.***>
发送时间: 2023年12月15日 3:40
收件人: AlexanderLabWHOI/EUKulele ***@***.***>
抄送: XU Wenqian ***@***.***>; Mention ***@***.***>
主题: Re: [AlexanderLabWHOI/EUKulele] some runs fail when downloading gtdb and marmmetsp (Issue #58)


Hi @shanexuuu<https://github.com/shanexuuu> thanks for reporting this. It might have been some link that got broken in the 2.0.7 release. To clarify, you are also getting the fasta and TSV file, just not the JSON?

―

**Comment by akrinos** [comment]
Hi both @shanexuuu and @danilodileo ! Figured this out. Changed the reference file to gzip but didn't update the script accordingly. While I fix this, you can use the workaround of 

```
create_protein_table.py --infile_peptide reference.pep.fa --infile_taxonomy tax-table.txt --outfile_json prot-map.json --output tax-table.txt --delim "/" --col_source_id Source_ID --taxonomy_col_id taxonomy --column SOURCE_ID
```

in the downloaded reference directory with a zcat or unzipped file. You can re-zip the reference peptide file afterwards, as a zipped database fasta file is fine for `EUKulele`
