### ISSUE TITLE
Run against Eukrprot database did not complete successfully and Eukprot update request 

### ISSUE THREAD

**Issue by mkarlik93** [AlexanderLabWHOI/EUKulele#66]
Hi, 

I have been trying to run EUKulele using Eukprot database, however run breaks at the step of taxonomic estimation:

Here you have log information:

Traceback (most recent call last):
  File "/home/karlicki/miniconda3/envs/EUKulele/lib/python3.7/site-packages/EUKulele/manage_steps.py", line 587, in manageTaxEstimation
    est_err_file,est_out_file)
  File "/home/karlicki/miniconda3/envs/EUKulele/lib/python3.7/site-packages/EUKulele/tax_placement.py", line 280, in place_taxonomy
    tax_table, classes = read_in_taxonomy(tax_file)
  File "/home/karlicki/miniconda3/envs/EUKulele/lib/python3.7/site-packages/EUKulele/tax_placement.py", line 69, in read_in_taxonomy
    tax_out.source_id = tax_out.source_id.astype(str)
  File "/home/karlicki/miniconda3/envs/EUKulele/lib/python3.7/site-packages/pandas/core/generic.py", line 5460, in __getattr__
    return object.__getattribute__(self, name)
AttributeError: 'DataFrame' object has no attribute 'source_id'

Taxonomic estimation did not complete successfully. Check log file for details.
AttributeError("'DataFrame' object has no attribute 'source_id'")

Could you please help with that?

Also, the provided eukprot db contains around 700 records, whereas the latest  V3 contains more then 900, it would be possible to update the database too?

We would love to run the tool on the freshwater metatranscriptomes and we need both mmetsp and eukprot running to get comprehensive taxonomic annotation. 

Thanks a lot!

**Comment by akrinos** [comment]
Hi @mkarlik93 !! So sorry for the delayed reply as a lot has happened this summer.

I have made and will soon deploy all the requested changes to `EUKulele` - 

- first, indeed the taxonomy table at present needs to have a column called "Source_ID" (any case is accepted) in order to run properly - this has been fixed in the new downloaded EukProt taxonomy table
- the new EukProt version is updated to use the datasets from EukProt v03.2021_11_22 with its 1100+ entries
- EukProt should now download properly in bioconda version 2.0.9 for `EUKulele`
